ryu:
  command: bash -c "cd /source && g++ a.cpp -o a &&  ryu-manager --observe-links *.py"
  image: rf37535/ryu:openstack
  ports:
    - 6633:6633
    - 8080:8080
  volumes:
    - "./Controller:/source"

mininet:
  image: rf37535/mininet:openflow13
  volumes:
    - "./Mininet:/source"
  privileged: true
